services:
  rule-api:
    build: .
    container_name: bun-rule-api
    env_file: .env
    environment:
      - PORT=4444
    networks:
      - oas
      - npm-network
    restart: unless-stopped

networks:
  oas:
    external: true
  npm-network:
    external: true
