services:
  rule-api:
    build: .
    container_name: rule-api
    ports:
      - "[::1]:4444:4444"
      - "127.0.0.1:4444:4444"
    env_file: .env
    environment:
      - PORT=4444
    networks:
      - oas

networks:
  oas:
    external: true