name: Deploy Live

# Trigger Points
on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Deploy to server
        uses: appleboy/ssh-action@master
        env:
          SECRET_PATH: ${{secrets.SECRET_PATH}}
          repo_path: ${{secrets.SECRET_PROJECT_PATH}}
          TOY_ENV: "Enjoy-deploy"
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSHKEY }}
          envs: SECRET_PATH
          script: |
            echo "Login To Machine Was SuccessFull"
            # echo "Here is your ToyENV - i'm $TOY_ENV"
            cd ~/server/rule-api/ && sh ./.scripts/live.sh